### PR TITLE
update to sqlcipher 4.3.0

### PR DESCRIPTION
**Pull request by zoff99**
I have tested and it works fine.
the only thing missing is an automatic upgrade procedure to upgrade the DB from sqlcipher 3.x to sqlcipher 4.x

### CODE REVIEW

**Comment by gfx** [comment]
Thanks for your pull-request! 💯 

By the way, please do not change the version on the repository which you send a pull-request to. This is irrelevant to what you'd like to fix.

**Comment by zoff99** [comment]
@gfx done

**Comment by gfx** [comment]
Thanks! 

(CI fails, but it doesn't seem to be related to this PR)

**Comment by gfx** [comment]
Will release a new version today.

**Comment by zoff99** [comment]
@gfx you can NOT release this as is!
sqlcipher 4.x Database is not compatible with sqlcipher 3.x Database.
it needs to be converted first

see: https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283

**Comment by zoff99** [comment]
either orma needs to detect this and convert the DB, transparent to the user.
or it needs to be documented that user application needs to convert.

**Comment by gfx** [comment]
Oh, really!? Hmm.

**Comment by zoff99** [comment]
@gfx can you now release this officially, otherwise i can't use sqlcipher 4.x with orma (and f-droid compile)?
maybe put some readme there to make sure devs do NOT just upgrade without writing an upgrade procedure in their apps.
if devs write new apps its no problem.

you could release it as 6.1.0 ? or 7.0.0 ?

what are your thoughts? would need that rather soonish.

**Pull request merged**
